openapi: 3.0.0
info:
  version: 2.0.0
  termsOfService: https://exoscale.com/terms
  contact:
    email: support@exoscale.com
    name: Exoscale Support
    url: https://portal.exoscale.com/tickets
  title: Exoscale ai-api-key crypto API
  description: Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
servers:
- url: https://api-{zone}.exoscale.com/v2
  variables:
    zone:
      default: ch-gva-2
      enum:
      - ch-gva-2
      - ch-dk-2
      - de-fra-1
      - de-muc-1
      - at-vie-1
      - at-vie-2
      - bg-sof-1
      - hr-zag-1
tags:
- description: A suite of cryptographic primitives offered by the Exoscale KMS.
  parent: kms
  externalDocs:
    description: Read more
    url: https://community.exoscale.com/documentation/kms/crypto
  name: crypto
  x-display-name: Cryptographic Operations
  x-weight: 1140
  x-icon: exo-ipv6
paths:
  /kms-key/{id}/decrypt:
    post:
      tags:
      - crypto
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/decrypt-response'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
      description: Decrypt a ciphertext.
      parameters:
      - in: path
        required: true
        name: id
        schema:
          type: string
          format: uuid
      summary: '[BETA] Decrypt'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/decrypt-request'
      operationId: decrypt
  /kms-key/{id}/encrypt:
    post:
      tags:
      - crypto
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/encrypt-response'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
      description: Encrypt a plaintext.
      parameters:
      - in: path
        required: true
        name: id
        schema:
          type: string
          format: uuid
      summary: '[BETA] Encrypt'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/encrypt-request'
      operationId: encrypt
  /kms-key/{id}/re-encrypt:
    post:
      tags:
      - crypto
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/re-encrypt-response'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
      description: Decrypts an existing ciphertext using its original key material and re-encrypts the underlying plaintext using a specified KMS key or the latest key material of the same KMS Key.
      parameters:
      - in: path
        required: true
        name: id
        schema:
          type: string
          format: uuid
      summary: '[BETA] Re-encrypt'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/re-encrypt-request'
      operationId: re-encrypt
  /kms-key/{id}/generate-data-key:
    post:
      tags:
      - crypto
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/generate-data-key-response'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
      description: Generate a Data Encryption Key from a given KMS Key.
      parameters:
      - in: path
        required: true
        name: id
        schema:
          type: string
          format: uuid
      summary: '[BETA] Generate Data Key'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/generate-data-key-request'
      operationId: generate-data-key
components:
  schemas:
    decrypt-response:
      type: object
      required:
      - plaintext
      properties:
        plaintext:
          type: string
          format: byte
    encrypt-request:
      type: object
      required:
      - plaintext
      properties:
        encryption-context:
          type: string
          format: byte
          nullable: true
        plaintext:
          type: string
          format: byte
    error-response:
      type: object
      description: RFC 9457 Problem Details error response
      required:
      - type
      - title
      - status
      - detail
      properties:
        type:
          type: string
          format: uri-reference
        title:
          type: string
        status:
          type: integer
          minimum: 100
          maximum: 599
        detail:
          type: string
        instance:
          type: string
          format: uri-reference
        errors:
          type: array
          items:
            type: object
            properties:
              path:
                type: string
              detail:
                type: string
              pointer:
                type: string
              location:
                type: string
    re-encrypt-response:
      type: object
      required:
      - ciphertext
      properties:
        ciphertext:
          type: string
          format: byte
    generate-data-key-response:
      type: object
      required:
      - plaintext
      - ciphertext
      properties:
        plaintext:
          type: string
          format: byte
        ciphertext:
          type: string
          format: byte
    generate-data-key-request:
      type: object
      properties:
        key-spec:
          type: string
          enum:
          - AES-256
        bytes-count:
          type: integer
          minimum: 1
          maximum: 1024
        encryption-context:
          type: string
          format: byte
          nullable: true
    re-encrypt-request:
      type: object
      required:
      - source
      - destination
      properties:
        source:
          type: object
          required:
          - key
          - ciphertext
          properties:
            key:
              type: string
              format: uuid
              description: The ID of the source key.
            encryption-context:
              type: string
              format: byte
              description: Optional encryption context appended to the AAD.
              nullable: true
            ciphertext:
              type: string
              format: byte
        destination:
          type: object
          required:
          - key
          properties:
            key:
              type: string
              format: uuid
              description: The ID of the target key.
            encryption-context:
              type: string
              format: byte
              description: Optional encryption context appended to the AAD.
              nullable: true
    encrypt-response:
      type: object
      required:
      - ciphertext
      properties:
        ciphertext:
          type: string
          format: byte
    decrypt-request:
      type: object
      required:
      - ciphertext
      properties:
        encryption-context:
          type: string
          format: byte
          nullable: true
        ciphertext:
          type: string
          format: byte
x-topics:
- title: API Request Signature
  content: '

    In order to authenticate legitimate users, the Exoscale API requires incoming requests to be signed using valid Exoscale API account credentials with the following mechanism.


    ## Signature Mechanism


    The *message* (i.e. content) to sign contains several segments concatenated using a line return character (`\n`).


    All segments must be included and in the described order. For cases where a segment doesn''t fit the context of the request (e.g. no request body) **an empty line must be used instead**.


    * Request method and request URL (path only), separated by a space character

    * Request body

    * Request URL parameters (Query String) values, concatenated without separator. The matching parameter names have to be specified in the resulting signature header `signed-query-args=` pragma, separated by semicolons (e.g. `p1;p2;pN`).

    * Request header values, concatenated without separator (none at the moment, leave empty)

    * Request expiration date in UNIX timestamp format


    Example *message* to sign for `GET /v2/resource/a02baf5a-a3e4-49a0-857b-8a08d276c1c0?p1=v1&p2=v2`:


    ```

    GET /v2/resource/a02baf5a-a3e4-49a0-857b-8a08d276c1c0


    v1v2


    1599140767

    ```


    The two blank lines above are due to the absence of a request body and signed headers.


    Example *message* to [create a security group](https://community.exoscale.com/reference/api/compute/security-group/#create-security-group)


    ```

    POST /v2/security-group

    {"name": "my-security-group"}



    1599140767

    ```


    The two blank lines above are due to the absence of query parameters and signed headers.


    The request signature consists of the base64-encoded [HMAC](https://en.wikipedia.org/wiki/HMAC) hash of the UTF-8 encoded *message* and the Exoscale API secret using the SHA265 function:


    ```

    signature = BASE64_ENCODE(HMAC_SHA256(Exoscale API secret, message))

    ```


    Finally, the computed signature must be added to the API request in a `Authorization` header such as:


    ```

    Authorization: EXO2-HMAC-SHA256 credential=<Exoscale API key>,expires=<expiration date UNIX timestamp>,signature=<signature>

    ```


    Example API query:


    ```

    GET /v2/resource/a02baf5a-a3e4-49a0-857b-8a08d276c1c0?p1=v1&p2=v2 HTTP/1.1

    Host: api-ch-gva-2.exoscale.com

    Authorization: EXO2-HMAC-SHA256 credential=EXO29147e9f89102b7ac1e88514,signed-query-args=p1;p2,expires=1599140767,signature=2AOBQsbElQb4FpKT/FM/9T4NobjlmZkSGvvdUth/xlY=

    ```


    ## Reference Implementations


    You can look up the following existing reference implementations:


    * Go: [github.com/exoscale/egoscale/api/v2 > `SecurityProviderExoscale.signRequest`](https://github.com/exoscale/egoscale/blob/master/v2/api/security.go)

    * Python: [requests-exoscale-auth > `ExoscaleV2Auth`](https://github.com/exoscale/requests-exoscale-auth/blob/master/exoscale_auth.py)


    '
- title: Zone local resources
  content: '

    The API is deployed across all Exoscale zones. When performing a compute call, you should use the relevant zone for your resource.

    For example: https://api-de-fra-1.exoscale.com/v2/instance would return only the instances from `de-fra-1`, https://api-ch-gva-2.exoscale.com/v2/instance from `ch-gva-2`.

    To obtain a list of all instances across all zones, you would need to do the corresponding request for each zone.

    '
